platform:ios, ‘7.0’
target “CloudPaletteBar” do
pod 'AFNetworking', '~> 3.1.0’
pod "JSONModel", "~> 1.2.0"
pod "MBProgressHUD", "~> 0.9.2"
pod "MJRefresh", "~>3.1.0”
pod 'SDWebImage', '~>3.7.5’
pod 'JPush'
pod 'FMDB', '~>2.6.2’
end